name: "transform"
profile: "transform"

model-paths: ["models"]

models:
  transform:
    +database: lake
    staging: { +materialized: view }
    intermediate: { +materialized: view }
    marts: { +materialized: table, +schema: marts }
